export const ON_IMAGE_ADD_REQUEST = 'ON_IMAGE_ADD_REQUEST'
export const ON_IMAGE_ADD_SUCCESS = 'ON_IMAGE_ADD_SUCCESS'
export const ON_IMAGE_ADD_FAILURE = 'ON_IMAGE_ADD_FAILURE'

export const ON_IMAGE_GET_REQUEST = 'ON_IMAGE_GET_REQUEST'
export const ON_IMAGE_GET_SUCCESS = 'ON_IMAGE_GET_SUCCESS'
export const ON_IMAGE_GET_FAILURE = 'ON_IMAGE_GET_FAILURE' 